version: '3'
services:
  react:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react_ui
    stdin_open: true
    volumes:
      - ./react_spa:/usr/src/app/spa
      - /usr/src/app/spa/node_modules
